import type { Voice } from "./api";

export const HARDCODED_VOICES: Voice[] = [
  {
    name: "zh-CN-YunxiNeural",
    display_name: "Yunxi",
    locale: "zh-CN",
    gender: "Male",
    language: "zh-CN",
    chinese_name: "云希",
    personality: "青年",
  },
  {
    name: "zh-CN-YunjianNeural",
    display_name: "Yunjian",
    locale: "zh-CN",
    gender: "Male",
    language: "zh-CN",
    chinese_name: "云健",
    personality: "运动",
  },
  {
    name: "zh-HK-WanLungNeural",
    display_name: "WanLung",
    locale: "zh-HK",
    gender: "Male",
    language: "zh-HK",
    chinese_name: "云龙",
    personality: "叙述",
  },
  {
    name: "zh-CN-YunyangNeural",
    display_name: "Yunyang",
    locale: "zh-CN",
    gender: "Male",
    language: "zh-CN",
    chinese_name: "云扬",
    personality: "新闻",
  },
  {
    name: "zh-CN-YunxiaNeural",
    display_name: "Yunxia",
    locale: "zh-CN",
    gender: "Male",
    language: "zh-CN",
    chinese_name: "云夏",
    personality: "可爱",
  },
  {
    name: "zh-CN-YunzheNeural",
    display_name: "Yunzhe",
    locale: "zh-CN",
    gender: "Male",
    language: "zh-CN",
    chinese_name: "云哲",
    personality: "沉稳",
  },
  {
    name: "zh-CN-XiaoxiaoNeural",
    display_name: "Xiaoxiao",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓晓",
    personality: "温柔",
  },
  {
    name: "zh-CN-XiaoyiNeural",
    display_name: "Xiaoyi",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓艺",
    personality: "活泼",
  },
  {
    name: "zh-CN-XiaozhenNeural",
    display_name: "Xiaozhen",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓甄",
    personality: "稳重",
  },
  {
    name: "zh-HK-HiuGaaiNeural",
    display_name: "HiuGaai",
    locale: "zh-HK",
    gender: "Female",
    language: "zh-HK",
    chinese_name: "晓佳",
    personality: "甜美",
  },
  {
    name: "zh-CN-XiaoniNeural",
    display_name: "Xiaoni",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓妮",
    personality: "成熟",
  },
  {
    name: "zh-HK-HiuMaanNeural",
    display_name: "HiuMaan",
    locale: "zh-HK",
    gender: "Female",
    language: "zh-HK",
    chinese_name: "晓雯",
    personality: "知性",
  },
  {
    name: "zh-CN-XiaobeiNeural",
    display_name: "Xiaobei",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓贝",
    personality: "可爱",
  },
  {
    name: "zh-CN-XiaoyuNeural",
    display_name: "Xiaoyu",
    locale: "zh-CN",
    gender: "Female",
    language: "zh-CN",
    chinese_name: "晓雨",
    personality: "清新",
  },
];
